name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: rm -rf dist/js dist/manifest.json
      - run: npm run build
      - run: npm run check-assets
      - run: npm run check-workers
      - uses: actions/upload-artifact@v4
        with:
          name: workers-report
          path: workers-report.json
      - run: npm run purge:cdn
